STYLED_SOUTHWEST_ARROW = "⇲" 

FILLED_BULLET_POINT     = "⦁"
EMPTY_BULLET_POINT      = "◦"

LONG_IMPL_RIGHTARROW    = "⟹"

WARNING_TRIANGLE        = "⚠"

DIVIDER_SYMBOL_UPPER    = "⚍"
DIVIDER_SYMBOL_DOWNER   = "⚎"