# ░█▀█░█░█░█▄█░█▀▀░░░░░░░█░█░█▀▀░█▀▀░█▀▄░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀░█░█░█▀▄░█▀█░▀█▀░▀█▀░█▀█░█▀█░░░█▀▀░▀█▀░█░░░█▀▀ 
# ░█▀▀░█▀▄░█░█░▀▀█░░▀░░░░█░█░▀▀█░█▀▀░█▀▄░░░█░░░█░█░█░█░█▀▀░░█░░█░█░█░█░█▀▄░█▀█░░█░░░█░░█░█░█░█░░░█▀▀░░█░░█░░░█▀▀
# ░▀░░░▀░▀░▀░▀░▀▀▀░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀░▀░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀░▀░░▀░░▀▀▀░▀▀▀░▀░▀░░░▀░░░▀▀▀░▀▀▀░▀▀▀

[USER_DATA]
NAME                = "sgommitos"

[PATHS]
# PKM related
PKM                 = "~/Desktop/pkms"               
DELETED_FILES       = "deleted"

# SW folder related
TEMPLATES           = "templates"                            

# External tools related 
PRINT_TOOL          = "cat" # you can also use more advanced MarkDown renderer, such as 'glow' -> https://github.com/charmbracelet/glow                                     
TEXT_EDITOR         = "micro"

[FILE_TYPES]
NOTES               = ".md"

[FILE_ORDER]
LIST                = "newer" # Available order filters: "alphabetic", "older", "newer"           

[TEMPLATES]
DAILY_NOTE_TEMPLATE = "daily_note_template"  

[SHORTCUTS]
# @NOTE: 'c' stands for 'CTRL' key
help  = "f1" # @EXAMPLE: 'f1' corresponds to hitting the F1 key
clear = "c-l"
exit  = "c-e"                           