# PKMS: User configuration file

[USER_DATA]
NAME = "sgommitos"

[PATHS]
PKM = "~/Desktop/pkms"               
TEXT_EDITOR = "micro"                  
DAILY = "daily"                     
TEMPLATES = "templates"             
FINANCES = "finances"               

[FILE_TYPES]
NOTES = ".md"

[FILE_ORDER]
LIST = "newer" # Available order filters: "alphabetic", "older", "newer"           

[TEMPLATES]
DAILY_NOTE_TEMPLATE = "daily_note_template"  

[SHORTCUTS]
# @NOTE: 'c' stands for 'CTRL' key
help  = "c-h" # @EXAMPLE: 'c-h' correspondes to hit 'CTRL + H' keys
clear = "c-l"
exit  = "c-e"                           