# PKMS: User configuration file

[USER_DATA]
NAME = "sgommitos"

[PATHS]
PKM = "~/Desktop/pkms"               
TEXT_EDITOR = "micro"                                       
TEMPLATES = "templates"                            

[FILE_TYPES]
NOTES = ".md"

[FILE_ORDER]
LIST = "newer" # Available order filters: "alphabetic", "older", "newer"           

[TEMPLATES]
DAILY_NOTE_TEMPLATE = "daily_note_template"  

[SHORTCUTS]
# @NOTE: 'c' stands for 'CTRL' key
help  = "f1" # @EXAMPLE: 'f1' corresponds to hitting the F1 key
clear = "c-l"
exit  = "c-e"                           